name: run-tests-in-develop-branch

on:
  push:
    branches: [ develop ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3.27'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Setup Database
      run: |
        sudo systemctl start mysql.service
        mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS test;'
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: testing
        DB_TEST_HOST: 127.0.0.1
        DB_TEST_PORT: 3306
        DB_TEST_DATABASE: test
        DB_TEST_USERNAME: root
        DB_TEST_PASSWORD: root
        SLACK_TOKEN: sample
        SLACK_ID_GENERAL: C01MGFXJSD8
        SLACK_ID_ADMINISTRATOR: U01MGFXHWF4
        SLACK_ID_MENTOR_CHANNEL: C01TCU28B28
        SLACK_ID_QUESTION_CHANNEL: C01SM8H8TDY
        SLACK_ID_MENTORS_NAME: 今川メンター,菊池メンター,工藤メンター,noppe(平野)メンター,山際メンター
        SLACK_ID_MENTORS_DESCRIPTION: Ruby、Scala、PHP、AWSなど,Kotlin、flutterなど,PHP、Go、ハッカソンの審査/勝ち方など,Swift、個人開発など,Python、Go、機械学習、就活相談など
        SLACK_ID_MENTORS_ID: U01PE3ZUX5E,U01SM47RJLT,UU6RPHQGG,UU6RPJUJU,UTZC4SKPV
      run: vendor/bin/phpunit
